/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.upcraft.winterjam

import dev.kord.common.entity.Snowflake
import dev.kordex.core.ExtensibleBot
import dev.kordex.core.utils.env
import dev.kordex.core.utils.envOfOrNull
import dev.kordex.core.utils.envOrNull
import dev.kordex.core.utils.loadModule
import dev.kordex.modules.web.core.backend.utils.web
import dev.upcraft.winterjam.extensions.whitelist.WhitelistExtension
import dev.upcraft.winterjam.util.DatabaseFactory
import dev.upcraft.winterjam.util.registerDataRepositories

val TEST_SERVER_ID = envOfOrNull<Snowflake>("TEST_SERVER")

// Get the bot' token from the env vars or a .env file
private val TOKEN = env("TOKEN")

suspend fun main() {
	val bot = ExtensibleBot(TOKEN) {
		applicationCommands {
			defaultGuild(TEST_SERVER_ID)
		}

		hooks {
			afterKoinSetup {
				loadModule {
					single { DatabaseFactory.create() }
				}
				registerDataRepositories()
			}
		}

		extensions {
			web {
				hostname = envOrNull("FRONTEND_URL")
				port = envOfOrNull<Int>("PORT") ?: 3000
			}

			add(::WhitelistExtension)
		}
	}

	bot.start()
}
