name: Build & Publish (main)
on:
  push:
    branches: [ main ]
    tags:
      - "*"

    paths-ignore:
      - ".github/**"
      - ".media/**"
      - "README**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name }}
